#!/usr/bin/env node
// Emit public/sitemap.xml from src/app/content/locales.json, filtered to the
// locales active for this build (committed `enabled` flags, or the local
// SPEAKWITH_LOCALES override), exactly as the router is.
//
// The same locale x route matrix feeds the router (app.routes.ts), the locale
// switcher and the hreflang alternates, so the sitemap cannot drift from what
// is actually prerendered. Runs as `prebuild`; the output is git-ignored and
// regenerated by CI, so a locally enabled locale never leaks into production.
// A single-locale build emits no xhtml:link alternates.
//
// Each localized page lists one <url> per locale, each carrying the full set
// of xhtml:link alternates (plus x-default), which is the form Google
// documents for sitemap-declared hreflang. Non-localized pages (legal) list
// their English URL only.
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ROOT, resolveActiveLocales } from './lib/active-locales.mjs';

const matrix = resolveActiveLocales();
const out = resolve(ROOT, 'public/sitemap.xml');
const multilingual = matrix.locales.length > 1;

const { origin, defaultLocale, locales, routes } = matrix;
const byCode = Object.fromEntries(locales.map(l => [l.code, l]));
const en = byCode[defaultLocale];

function pathFor(route, locale) {
  const prefix = route.localized ? locale.prefix : '';
  const segments = [prefix, route.path].filter(Boolean);
  return segments.length ? `/${segments.join('/')}/` : '/';
}

const entries = [];
for (const route of routes) {
  const targets = route.localized ? locales : [en];
  const alternates = route.localized && multilingual
    ? [
        ...locales.map(l => ({ hreflang: l.htmlLang, href: origin + pathFor(route, l) })),
        { hreflang: 'x-default', href: origin + pathFor(route, en) },
      ]
    : [];
  for (const locale of targets) {
    const lines = [`  <url>`, `    <loc>${origin}${pathFor(route, locale)}</loc>`];
    for (const alt of alternates) {
      lines.push(`    <xhtml:link rel="alternate" hreflang="${alt.hreflang}" href="${alt.href}"/>`);
    }
    lines.push(`    <priority>${route.priority}</priority>`, `  </url>`);
    entries.push(lines.join('\n'));
  }
}

const xml = [
  `<?xml version="1.0" encoding="UTF-8"?>`,
  `<!-- Generated by scripts/generate-sitemap.mjs from src/app/content/locales.json. Do not edit by hand. -->`,
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">`,
  ...entries,
  `</urlset>`,
  ``,
].join('\n');

writeFileSync(out, xml);
console.log(`sitemap: ${entries.length} URLs (${matrix.locales.map(l => l.code).join(', ')}) -> ${out}`);
