#!/usr/bin/env node
// Write src/app/content/locales.active.ts: the locale matrix filtered to the
// locales active for this build, plus static imports of ONLY their copy
// files, so a disabled locale contributes no routes and no strings to the
// bundle. Generated and git-ignored; runs as pre{start,build,watch,test}.
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ROOT, resolveActiveLocales } from './lib/active-locales.mjs';

const matrix = resolveActiveLocales();
const out = resolve(ROOT, 'src/app/content/locales.active.ts');
const extra = matrix.locales.filter(l => l.code !== matrix.defaultLocale);

const imports = extra.map((l, i) => `import L${i} from './copy.${l.code}.json';`).join('\n');
const entries = extra.map((l, i) => `  '${l.code}': L${i},`).join('\n');
const publicMatrix = {
  origin: matrix.origin,
  defaultLocale: matrix.defaultLocale,
  locales: matrix.locales.map(({ enabled, ...l }) => l),
  routes: matrix.routes,
};

const ts = `// GENERATED by scripts/resolve-locales.mjs from locales.json. Do not edit; git-ignored.
// Active locales for this build (${matrix.source}): ${matrix.locales.map(l => l.code).join(', ')}
${imports}

export const ACTIVE_MATRIX = ${JSON.stringify(publicMatrix, null, 2)} as const;

export const ACTIVE_TRANSLATIONS: Record<string, unknown> = {
${entries}
};
`;
writeFileSync(out, ts);
console.log(`locales: ${matrix.locales.map(l => l.code).join(', ')} (${matrix.source})`);
if (matrix.overridden) {
  console.log('locales: SPEAKWITH_LOCALES override is LOCAL ONLY; production ships the committed enabled flags');
}
